### ISSUE TITLE
[Bug] Incorrect signature hash during verify return url

### ISSUE THREAD

**Issue by tachibanayui** [lehuygiang28/vnpay#15]
Method [verifyReturnUrl](https://github.com/lehuygiang28/vnpay/blob/main/src/vnpay.ts#L261) divides by 100 before verifying the signature which leads to a signature mismatch between VNPay API and our hash.

**Comment by lehuygiang28** [comment]
Oh, I see it can be divided by 100 twice. Thank you. I will fix it ASAP.

**Comment by tachibanayui** [comment]
Please publish an update on npm after you resolve this bug, thank you.

**Comment by lehuygiang28** [comment]
Hi, I fixed it in [v1.5.1](https://www.npmjs.com/package/vnpay/v/1.5.1). Please let me know if you have any issues. Thank you!
