### ISSUE TITLE
[Question] Why am I getting `isVerified: false` and `message: "Wrong checksum"`?

### ISSUE THREAD

**Issue by whitersun** [lehuygiang28/vnpay#17]
chào bác, cho mình xin hỏi sau khi payment thành công và mình nhận được kết quả verify fail của verifyReturnUrl. Message mình nhận được là Wrong checksum là thế nào vậy bác. Lỗi mơ hồ quá, mình không hiểu được lắm, mong được bác giúp đỡ ạ.
![image](https://github.com/lehuygiang28/vnpay/assets/37898596/8676c3ed-0f70-42ae-b6c1-035d9bc74d16)

Phía hình dưới là data mình nhận được sau khi payment success.
![image](https://github.com/lehuygiang28/vnpay/assets/37898596/ded027d6-02cf-4748-9313-0f5d9fb91366)

**Comment by lehuygiang28** [comment]
Chào bạn,

Bạn nhận được
> kết quả verify fail của verifyReturnUrl. Message mình nhận được là Wrong checksum

là do quá trình xác thực `vnp_SecureHash` từ vnpay trả về thất bại, có thể là bug #15, bạn update lên version mới nhất nha.

**Comment by whitersun** [comment]
OK bạn, để mình thử phát, cảm ơn bạn nhé ❤️
