### ISSUE TITLE
Transaction not found when refund

### ISSUE THREAD

**Issue by anhledger12** [lehuygiang28/vnpay#28]
Em có tích hợp refund vào trong hệ thống của em thì khi Refund bên vnpay trả về transaction not found mặc dù em đã kiểm tra trên web của merchant thì có transaction đó và trong database của em các thông tin cũng đều trùng với thông tin vnpay gửi về. Lý do vì sao vậy ạ.

**Comment by lehuygiang28** [comment]
Bạn cần cung cấp đầy đủ và đúng nhất các trường bắt buộc theo [docs của vnpay](https://sandbox.vnpayment.vn/apis/docs/truy-van-hoan-tien/querydr&refund.html#danh-s%C3%A1ch-tham-s%E1%BB%91-refund) và của hàm [refund](https://vnpay.js.org/refund) như là `vnp_Amount, vnp_OrderInfo, vnp_TransactionDate, vnp_TransactionNo, vnp_TxnRef, ...` nha.

Mình vừa kiểm tra thì vẫn nhận được phản hồi thành công ạ
![image](https://github.com/user-attachments/assets/6c3d7102-9447-4b49-962b-a563f896dd9b)
