### ISSUE TITLE
Hỏi về VNP QR code

### ISSUE THREAD

**Issue by namnp201002** [lehuygiang28/vnpay#7]
Bạn cho mình hỏi, bên VN Pay có hỗ trợ API tạo QR Code chưa nhỉ?

**Comment by lehuygiang28** [comment]
Ý bạn là tạo QR để redirect sang VNPay, hay QR để thanh toán ngay.

- QR redirect: Hiện mình chưa thấy trong docs của `vnpay` có phần để tạo QR. Vì vậy bạn sẽ phải tự viết hoặc dùng các thư viện khác.
- QR payment: QR để thanh toán, tùy account đăng kí sandbox với `vnpay` sẽ có thêm tùy chọn thanh toán bằng QR ở trang thanh toán. Mình cũng chưa rõ lí do là gì.

Trên đây là trả lời của mình, nếu bạn có phát hiện gì mới hãy cập nhật giúp mình nhé, cảm ơn bạn!
